/*
 You are given two strings s and t.
 
 String t is generated by random shuffling string s and then add one more letter at a random position.
 
 Return the letter that was added to t.
 
 Example 1:
 
 Input: s = "abcd", t = "abcde"
 Output: "e"
 Explanation: 'e' is the letter that was added.
 Example 2:
 
 Input: s = "", t = "y"
 Output: "y"
 */

import Foundation

func findTheDifferentChar(_ s: String, _ t: String) -> Character {
    var result: UInt8 = 0
    
    // XOR all characters in the first string
    for char in s.utf8 {
        result ^= char
        
    }
    
    // XOR all characters in the second string
    for char in t.utf8 {
        result ^= char
        
    }
    // Convert the resulting byte back to a Character
    return Character(Unicode.Scalar(result))
    
}

let s = "abcd"
let t = "abxcd"

let result = findTheDifferentChar(s, t)
print("findTheDifferentChar  : \(result)")
